version: "3.9"
services:
    nginx:
        image: "nginx:alpine"
        #restart: always
        working_dir: /app
        links:
            - php-fpm
        volumes:
            - ".:/app"
            - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "80:80"

    php-fpm:
        build: docker/php-fpm
        #restart: always
        working_dir: /app
        #links:
        #    - mariadb
        volumes:
            - ".:/app"
            - "./docker/php-fpm/php-overrides.ini:/usr/local/etc/php/conf.d/php-overrides.ini"